/**
 * GENERATED by scripts/generate-anatomy-manifest.js — do not edit by hand.
 * Canonical production asset identities, byte sizes, and SHA-256 hashes,
 * verified against the actual optimized GLBs at generation time.
 *
 * `file` is the production filename (unprefixed; identity is completed by
 * `bodyModel`). Recommended static-host layout: `<base>/<bodyModel>/<file>`.
 * Local dev serves a flat subset under `/models-dev/` with `female-`-prefixed
 * copies — see devAssetFilename(). No host, backend, or database involved.
 *
 * Production vs dev resolution is handled by buildAssetUrl()/getManifestAssetUrl():
 * - dev base `/models-dev/` → flat with female- prefix (preserves public/models-dev/*.glb)
 * - any other base (HTTPS static host) → `<base>/<bodyModel>/<file>` (provider-neutral)
 * See docs/architecture/asset-hosting.md for hosting, caching, and versioning.
 */
import type { AnatomyBodyModelKey, AnatomySystemKey } from '@anatomiax/shared-types';

export interface AssetManifestEntry {
  bodyModel: AnatomyBodyModelKey;
  system: AnatomySystemKey;
  /** Production filename (unprefixed). */
  file: string;
  /** Exact byte size of the hashed file. */
  bytes: number;
  /** Lowercase hex SHA-256 of the exact file bytes. */
  sha256: string;
}

export const ASSET_MANIFEST: readonly AssetManifestEntry[] = [
  {
    bodyModel: 'male',
    system: 'skin',
    file: 'skin-meshopt.glb',
    bytes: 668896,
    sha256: 'afe1a8891a7ef66e6629dda19b571a216c686729ed84a36f12e8b67dafa41f50',
  },
  {
    bodyModel: 'male',
    system: 'musculoskeletal',
    file: 'musculoskeletal-meshopt.glb',
    bytes: 4329744,
    sha256: '7a4da600bce2f4666efc076b123980e3f9eba0b6b12bf46c1f74a217d459c1e7',
  },
  {
    bodyModel: 'male',
    system: 'nervous',
    file: 'nervous-meshopt.glb',
    bytes: 13449672,
    sha256: '6ee47b4eff36671c1007affd7162403ef586573406946fe4354763ed400d5ed2',
  },
  {
    bodyModel: 'male',
    system: 'cardiovascular',
    file: 'cardiovascular-meshopt.glb',
    bytes: 3752528,
    sha256: 'a05314c6f1dbb6da65a27578b3fdcfca80a0fd477db2da1c99b954f75751d8bf',
  },
  {
    bodyModel: 'male',
    system: 'respiratory',
    file: 'respiratory-meshopt.glb',
    bytes: 2434080,
    sha256: '1a433bb70c30a0e00639cbdd930b59e306cb1100183c6b978e6a354dd9859c64',
  },
  {
    bodyModel: 'male',
    system: 'digestive',
    file: 'digestive-meshopt.glb',
    bytes: 1711640,
    sha256: '4f3690047453f6dbb2ac55d1115d494a904b0b2e8a21e68c497c97315e0c956a',
  },
  {
    bodyModel: 'male',
    system: 'urinary',
    file: 'urinary-meshopt.glb',
    bytes: 1230820,
    sha256: 'b228d2bff817043fc9c74da1cc56d095c1b4792811769d3aee85f0ccea4f60a1',
  },
  {
    bodyModel: 'male',
    system: 'reproductive',
    file: 'reproductive-meshopt.glb',
    bytes: 959984,
    sha256: 'ecc5f450a425db97c731716fc30962deea4ea4a010696e0af29d51c27761b039',
  },
  {
    bodyModel: 'male',
    system: 'lymphatic',
    file: 'lymphatic-meshopt.glb',
    bytes: 1250436,
    sha256: 'ccf4dff9acc91878c1545322a3a7e360c87779461cb327aa923c0f192f969f79',
  },
  {
    bodyModel: 'female',
    system: 'skin',
    file: 'skin-meshopt.glb',
    bytes: 7926072,
    sha256: '9bc5494bea714791b282fe4f6de8791466794d10d95964c51536c8410e4d3658',
  },
  {
    bodyModel: 'female',
    system: 'musculoskeletal',
    file: 'musculoskeletal-meshopt.glb',
    bytes: 3721584,
    sha256: 'd2ef31e5fbba92e06fa90103933ca3a28c62148434bc9ba1098f368eb28932fc',
  },
  {
    bodyModel: 'female',
    system: 'nervous',
    file: 'nervous-meshopt.glb',
    bytes: 14495144,
    sha256: 'c083095732f08e909753eeacf956f07fee4bb9e9a918aa8bda12a61b6983cfef',
  },
  {
    bodyModel: 'female',
    system: 'cardiovascular',
    file: 'cardiovascular-meshopt.glb',
    bytes: 3371684,
    sha256: 'ba4e24ff6eb365df3140c22807f1dc39619831c05ae8f77c433625463e358d91',
  },
  {
    bodyModel: 'female',
    system: 'respiratory',
    file: 'respiratory-meshopt.glb',
    bytes: 4667936,
    sha256: 'bd56a9b7b78a07643cf2b6d6a4b20e694b242330c93c36c173ebecd4174eb1b2',
  },
  {
    bodyModel: 'female',
    system: 'digestive',
    file: 'digestive-meshopt.glb',
    bytes: 1408788,
    sha256: 'a1fbea96d121c01c1bcafdc28c62cca8b654ec94d6fc878e7a4a02ca4217d3ab',
  },
  {
    bodyModel: 'female',
    system: 'urinary',
    file: 'urinary-meshopt.glb',
    bytes: 1290180,
    sha256: 'ac82652cdf03b09b4a537070b38b30fbf4b5493123a120e609ce2b6cf9f7efe5',
  },
  {
    bodyModel: 'female',
    system: 'reproductive',
    file: 'reproductive-meshopt.glb',
    bytes: 1558604,
    sha256: '5fff5772e5d43063c6d2dcc4ceb4b30804ee81dd2851a56032828ff7ff8118be',
  },
  {
    bodyModel: 'female',
    system: 'lymphatic',
    file: 'lymphatic-meshopt.glb',
    bytes: 1195116,
    sha256: '8b6512615d888dd08e8f5d737d8518b84ab2d1711824cd24233a55a7ca506fde',
  },
];

export function findManifestEntry(
  bodyModel: AnatomyBodyModelKey,
  system: AnatomySystemKey
): AssetManifestEntry | undefined {
  return ASSET_MANIFEST.find(e => e.bodyModel === bodyModel && e.system === system);
}

/**
 * Local-dev flat-layout filename: male entries are served unprefixed while
 * female entries are served as `female-<file>` under `/models-dev/`.
 * Production/hosted layouts must use `file` (with `bodyModel` as identity).
 */
export function devAssetFilename(bodyModel: AnatomyBodyModelKey, file: string): string {
  return bodyModel === 'female' ? `female-${file}` : file;
}

/**
 * Normalizes a static-host base URL to always end with `/`.
 * Empty or undefined falls back to `/models-dev/` (local dev).
 */
export function normalizeAssetBase(base: string | undefined | null): string {
  const raw = (base ?? '').trim() || '/models-dev/';
  return raw.endsWith('/') ? raw : `${raw}/`;
}

/**
 * Provider-neutral asset URL builder.
 * - `/models-dev/` (local dev) → flat layout with female- prefix, preserves existing public/models-dev/*.glb.
 * - any other base (e.g. https://assets.example/anatomy/) → `<base>/<bodyModel>/<file>` for 18 GLBs.
 * The manifest carries no host; this function completes identity with bodyModel.
 */
export function buildAssetUrl(
  base: string | undefined | null,
  bodyModel: AnatomyBodyModelKey,
  file: string
): string {
  const normalized = normalizeAssetBase(base);
  if (normalized === '/models-dev/') {
    return `${normalized}${devAssetFilename(bodyModel, file)}`;
  }
  return `${normalized}${bodyModel}/${file}`;
}

/**
 * Resolves a manifest entry to its full URL under the given base.
 */
export function getManifestAssetUrl(
  base: string | undefined | null,
  entry: AssetManifestEntry
): string {
  return buildAssetUrl(base, entry.bodyModel, entry.file);
}

/**
 * All 18 production URLs under the given base — deterministic ordering (male then female, system order).
 */
export function getAllProductionUrls(base: string | undefined | null): string[] {
  return ASSET_MANIFEST.map(e => getManifestAssetUrl(base, e));
}

/**
 * Cache-safe versioned URL using the manifest SHA-256.
 * Filenames are preserved; versioning is via `?v=<shortHash>` query param
 * (first 8 hex chars) so existing references do not break and immutable
 * caching can be applied. Full SHA-256 remains in the manifest for integrity.
 * Example: https://assets.example/anatomy/male/skin-meshopt.glb?v=afe1a889
 */
export function getVersionedAssetUrl(
  base: string | undefined | null,
  entry: AssetManifestEntry
): string {
  const url = getManifestAssetUrl(base, entry);
  const short = entry.sha256.slice(0, 8);
  return `${url}?v=${short}`;
}
